"use client";
import { useState } from "react";
import type { Message } from "./ConversationLog";

interface Props {
  messages: Message[];
}

export default function ConversationExport({ messages }: Props) {
  const [copied, setCopied] = useState(false);

  const buildText = () => {
    const header = `GestureTalk — Conversation Export\nDate: ${new Date().toLocaleString("en-IN")}\nTotal messages: ${messages.length}\n${"─".repeat(40)}\n\n`;
    const body = messages
      .map((m) => {
        const time = new Date(m.timestamp).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
        return `[${time}] ${m.text}`;
      })
      .join("\n");
    return header + body;
  };

  const downloadTxt = () => {
    const content = buildText();
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gesturetalk-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadHtml = () => {
    const rows = messages
      .map((m) => {
        const time = new Date(m.timestamp).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
        const urgent = ["help", "emergency", "pain", "can't breathe", "doctor"].some((k) =>
          m.text.toLowerCase().includes(k)
        );
        return `<tr style="background:${urgent ? "#fef2f2" : "#fff"}">
  <td style="padding:6px 10px;color:#666;white-space:nowrap">${time}</td>
  <td style="padding:6px 10px;font-weight:${urgent ? "bold" : "normal"};color:${urgent ? "#dc2626" : "#111"}">${urgent ? "🚨 " : ""}${m.text}</td>
</tr>`;
      })
      .join("\n");

    const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>GestureTalk Export</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:20px}
h1{color:#0c1120}table{width:100%;border-collapse:collapse}
tr:nth-child(even){background:#f9fafb}td{border-bottom:1px solid #e5e7eb}
.header{background:#0c1120;color:#fff;padding:20px;border-radius:8px;margin-bottom:24px}
</style></head><body>
<div class="header">
  <h1>🤟 GestureTalk — Communication Log</h1>
  <p>Patient communication record · Exported ${new Date().toLocaleString("en-IN")}</p>
  <p>${messages.length} messages recorded</p>
</div>
<table><thead><tr style="background:#f3f4f6">
<th style="padding:8px 10px;text-align:left">Time</th>
<th style="padding:8px 10px;text-align:left">Message</th>
</tr></thead><tbody>${rows}</tbody></table>
<p style="margin-top:20px;color:#888;font-size:12px">Generated by GestureTalk · All data processed on-device · No data uploaded</p>
</body></html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gesturetalk-${new Date().toISOString().slice(0, 10)}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(buildText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement("textarea");
      ta.value = buildText();
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (messages.length === 0) {
    return (
      <div className="text-center py-4 text-gray-500 text-sm">No messages to export yet.</div>
    );
  }

  return (
    <div className="space-y-2">
      <p className="text-xs text-gray-500">{messages.length} messages ready to export</p>
      <div className="flex flex-col gap-2">
        <button
          onClick={downloadTxt}
          className="flex items-center gap-3 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white text-sm px-4 min-h-[44px] rounded-xl transition-colors touch-manipulation"
          aria-label="Download as text file"
        >
          <span className="text-xl">📄</span>
          <div className="text-left">
            <div className="font-medium">Download .txt</div>
            <div className="text-xs text-gray-400">Plain text for printing or EHR paste</div>
          </div>
        </button>

        <button
          onClick={downloadHtml}
          className="flex items-center gap-3 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white text-sm px-4 min-h-[44px] rounded-xl transition-colors touch-manipulation"
          aria-label="Download as formatted report"
        >
          <span className="text-xl">📊</span>
          <div className="text-left">
            <div className="font-medium">Download report (.html)</div>
            <div className="text-xs text-gray-400">Formatted report with urgent flags highlighted</div>
          </div>
        </button>

        <button
          onClick={copyToClipboard}
          className="flex items-center gap-3 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white text-sm px-4 min-h-[44px] rounded-xl transition-colors touch-manipulation"
          aria-label="Copy all messages to clipboard"
        >
          <span className="text-xl">{copied ? "✅" : "📋"}</span>
          <div className="text-left">
            <div className="font-medium">{copied ? "Copied!" : "Copy to clipboard"}</div>
            <div className="text-xs text-gray-400">Paste into WhatsApp, email, or hospital notes</div>
          </div>
        </button>

        {typeof navigator !== "undefined" && "share" in navigator && (
          <button
            onClick={() => {
              (navigator as Navigator & { share: (d: object) => Promise<void> }).share({
                title: "GestureTalk Communication Log",
                text: buildText(),
              }).catch(() => {});
            }}
            className="flex items-center gap-3 bg-blue-900/40 hover:bg-blue-800/50 border border-blue-800/50 text-blue-300 text-sm px-4 min-h-[44px] rounded-xl transition-colors touch-manipulation"
            aria-label="Share via system share sheet"
          >
            <span className="text-xl">📤</span>
            <div className="text-left">
              <div className="font-medium">Share via phone</div>
              <div className="text-xs text-blue-400/70">WhatsApp, SMS, email from your device</div>
            </div>
          </button>
        )}
      </div>
    </div>
  );
}
