"use client";
import { useState, useCallback } from "react";
import type { Message } from "./ConversationLog";

interface Props {
  messages: Message[];
  patientName?: string;
}

export default function SOAPNote({ messages, patientName }: Props) {
  const [note, setNote] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [latency, setLatency] = useState<number | null>(null);
  const [isDemo, setIsDemo] = useState(false);
  const [copied, setCopied] = useState(false);

  const generate = useCallback(async () => {
    if (!messages.length) return;
    setLoading(true);
    setNote("");
    const start = Date.now();

    try {
      const res = await fetch("/api/gemma-soap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: messages.slice(-30), // last 30 messages for context
          patientName: patientName ?? "Patient",
          wardContext: "General ward, Indian government hospital",
        }),
        signal: AbortSignal.timeout(18000),
      });
      const data = await res.json();
      setNote(data.note ?? "");
      setLatency(data.latencyMs ?? Date.now() - start);
      setIsDemo(data.offline ?? false);
    } catch {
      setNote(DEMO_NOTE);
      setIsDemo(true);
    } finally {
      setLoading(false);
    }
  }, [messages, patientName]);

  const copy = async () => {
    await navigator.clipboard.writeText(note).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const print = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>SOAP Note — GestureTalk</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:20px;line-height:1.6}
h1{color:#0c1120;border-bottom:2px solid #06b6d4;padding-bottom:8px}
pre{white-space:pre-wrap;font-family:inherit;font-size:14px}
.meta{color:#666;font-size:12px;margin-bottom:20px}
</style></head><body>
<h1>🤟 GestureTalk — Clinical SOAP Note</h1>
<div class="meta">Patient: ${patientName ?? "Patient"} · Generated: ${new Date().toLocaleString("en-IN")} · Powered by Gemma 4</div>
<pre>${note}</pre>
<p style="margin-top:30px;color:#999;font-size:11px">Generated by GestureTalk AAC · All AI processing on-device via Gemma 4</p>
</body></html>`);
    win.print();
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-xs font-bold uppercase text-gray-500">📋 Gemma 4 Clinical SOAP Note</h3>
          <p className="text-xs text-gray-600 mt-0.5">AI-generated from conversation · for nurse handoff</p>
        </div>
        {latency && (
          <span className="text-[10px] text-gray-600 font-mono">{latency}ms</span>
        )}
      </div>

      {!note ? (
        <button
          onClick={generate}
          disabled={loading || messages.length === 0}
          className="w-full flex items-center justify-center gap-2 bg-blue-900/30 hover:bg-blue-800/40 disabled:opacity-40 border border-blue-700/50 text-blue-300 font-bold min-h-[52px] rounded-xl transition-colors text-sm"
          aria-label="Generate clinical SOAP note from conversation"
        >
          {loading ? (
            <>
              <span className="w-4 h-4 border-2 border-blue-400 border-t-transparent rounded-full animate-spin" />
              Gemma 4 generating SOAP note…
            </>
          ) : (
            <>{messages.length === 0 ? "No messages yet" : "✨ Generate SOAP Note with Gemma 4"}</>
          )}
        </button>
      ) : (
        <div className="space-y-3">
          {isDemo && (
            <div className="text-[10px] text-amber-400 bg-amber-900/20 border border-amber-700/30 rounded-lg px-3 py-1.5">
              🎬 Demo note — connect Gemma 4 via Ollama for real AI generation
            </div>
          )}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-4">
            <pre className="text-xs text-gray-300 whitespace-pre-wrap font-mono leading-relaxed">
              {note}
            </pre>
          </div>
          <div className="flex gap-2">
            <button
              onClick={copy}
              className="flex-1 flex items-center justify-center gap-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white text-xs min-h-[40px] rounded-xl transition-colors"
            >
              {copied ? "✅ Copied" : "📋 Copy"}
            </button>
            <button
              onClick={print}
              className="flex-1 flex items-center justify-center gap-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white text-xs min-h-[40px] rounded-xl transition-colors"
            >
              🖨️ Print
            </button>
            <button
              onClick={() => { setNote(""); setLatency(null); }}
              className="flex items-center justify-center bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-400 text-xs min-h-[40px] px-3 rounded-xl transition-colors"
            >
              ↺
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

const DEMO_NOTE = `SUBJECTIVE
Patient communicated via GestureTalk AAC device. Key complaints:
- "I am in severe pain — level 8" (repeated 2×)
- "I cannot breathe — emergency" (high urgency)
- "Please call my family"
Patient appears distressed based on gesture emotion detection.

OBJECTIVE
AAC session duration: ~15 minutes. 12 total messages recorded.
Emotion detection: distressed (confidence 0.91), pain indicators noted.
Communication pattern: escalating urgency across session.

ASSESSMENT
Patient reporting severe pain (8/10) and breathing difficulty. 
Communication suggests acute distress requiring immediate clinical attention.
Emotional state consistent with pain crisis based on Gemma 4 vision analysis.

PLAN
1. Immediate pain assessment and vitals check
2. Respiratory evaluation — patient reported breathing difficulty
3. Notify attending physician
4. Contact patient's family as requested
5. Continue AAC support — patient is communicating effectively

HANDOFF NOTE
Patient in acute distress, reporting pain 8/10 and breathing difficulty via AAC device. 
Physician review needed. Family contact requested by patient.`;
